config/routes.rb
Library::Application.routes.draw do

  get "subjects/index"
  root :to=>'subjects#index'
  resources :subjects
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :subject

  attr_accessible :title, :description, :subject_id

  validates_presence_of :title,:description

  validates_uniqueness_of :title

  validates_length_of :title, :in=>3..20

  validates_length_of :description, :minimum=>5

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  
  has_many :books, :dependent=> :destroy

  attr_accessible :name
  
  validates_presence_of :name

  validates_uniqueness_of :name

  validates_length_of :name, :in=>3..10

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_filter :self_load, :only=>[:edit,:show,:update,:destroy]

  def index
    @books=Book.where(:subject_id=>params[:id])
  end

  def new 
    @book=Book.new
    @subjects=Subject.all
  end

  def create 
    @book=Book.new(params[:book])
       if @book.save
        redirect_to root_url, :notice=>'New Book has been saved'
       else 
        render :action=>'new'
       end
  end

  def edit
  end

  def update
    if @book.update_attributes(params[:book])
       redirect_to books_path, :notice=>'Book has been updated'
    else
       render :action=>'edit'
    end
  end

  def show
  end

  def destroy
    @book.destroy
    redirect_to root_url
  end

  def self_load
    @book=Book.find(params[:id])
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
 
  before_filter :self_load, :only=>[:edit,:show,:update,:destroy]

  def index
    @subjects=Subject.all
    @books=Book.all
  end

  def new 
    @subject=Subject.new
  end

  def create 
    @subject=Subject.new(params[:subject])
    if @subject.save
       redirect_to root_url, :notice=>'New subject has been added'
    else 
       render :action=>'new'
    end
  end

  def edit
  end

  def update
    if @subject.update_attributes(params[:subject])
       redirect_to root_url, :notice=>'Subject has been updated'
    else
       render :action=>'edit'
    end
  end

  def show
  end

  def destroy
    @subject.destroy
    redirect_to root_url
  end

  def self_load
    @subject=Subject.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/books/edit.html.erb
<h2> Edit book </h2>

<%= form_for(@book) do |f| %>
 <% if @book.errors.any? %>
   <ul><% @book.errors.full_messages.each do |m| %>
   <li><%= m %></li>
   <% end %></ul>
 <% end %>

<table>

<tr><td><b><%= f.label 'Title' %></b></td>
    <td><%= f.text_field :title %></td></tr>

<tr><td><b><%= f.label 'Description' %></b></td>
    <td><%= f.text_field :description %></td></tr>

<tr><td><%= f.submit 'Save Changes' %></td></tr>

</table>
<% end %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if @books.blank? %>
  <p> No Books </p>
<% else %>
   <% @books.each do |book| %>
   <ul><li><p>
   <%= link_to book.title, book %>
   <%= link_to 'Edit', { :action=>'edit', :id=>book.id } %>
   <%= link_to 'Delete', book, method: :delete, confirm: 'Are you sure?' %>
   </p></li></ul>
  <% end %>
<% end %>

<%= link_to 'Back', root_url %>

app/views/books/new.html.erb
<h2> Add New Book </h2>
<%= form_for(@book) do |f| %>
 <% if @book.errors.any? %>
      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  <% end %>


<table>

<tr><td><b><%= f.label 'Title' %></b></td>
    <td><%= f.text_field :title %></td></tr>

<tr><td><b><%= f.label 'Description' %></b></td>
    <td><%= f.text_area :description %></td></tr>

<tr><td><b><%= f.label 'Subject' %></b></td>
    <td><%= f.collection_select(:subject_id,@subjects,:id,:name) %></td></tr>

<tr><td><%= f.submit 'Save' %></td></tr>

</table>

<% end %>

<%= link_to 'Back', root_url %>

app/views/books/show.html.erb
<p><b>Title :</b>
<%= @book.title %></p>
<p><b>Desvription :</b>
<%= @book.description %></p>
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] if flash[:notice].present? %>
<%= yield %>

</body>
</html>

app/views/subjects/edit.html.erb
<h2> Edit Subject </h2>
<%= form_for(@subject) do |f| %>
 <% if @subject.errors.any? %>
   <ul><% @subject.errors.full_messages.each do |m| %>
   <li><%= m %></li>
   <% end %></ul>
 <% end %>
<%= f.label 'Subject Name' %>
<%= f.text_field :name %>
<%= f.submit 'Save Changes' %>
<% end %>
<%= link_to 'Back', root_url %>

app/views/subjects/index.html.erb
<% if @subjects.blank? %>
  <p> No Books in the library </p>
<% else %>
  <% @subjects.each do |subject| %>
<ul><li><p>
   <%= link_to subject.name, books_path(:id=>subject.id) %>
   <%= link_to 'Edit', { :action=>'edit', :id=>subject.id } %>
   <%= link_to 'Delete', subject, method: :delete, confirm: 'Are you sure?' %></p></li></ul>
  <% end %>
<% end %>
<%= link_to 'New Subject', new_subject_path %><br/>
<%= link_to 'New Book', new_book_path %>

app/views/subjects/new.html.erb
<h2> Add New Subject </h2>
<%= form_for(@subject) do |f| %>
 <% if @subject.errors.any? %>
  <ul>
     <% @subject.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
     <% end %>
  </ul>
 <% end %>
<p><%= f.label 'Subject Name' %>
<%= f.text_field :name %></p>
<%= f.submit 'Save' %>
<% end %>
<%= link_to 'Back', root_url %>

app/views/subjects/show.html.erb
<p><b>Subject Name :</b>
<%= @subject.name %></p>
<%= link_to 'Back', root_url %>